name: Branch Protection

on:
    push:
        branches: ['main']

jobs:
    check-branch:
        runs-on: ubuntu-latest
        steps:
            - name: Check if push is direct to main
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              run: |
                  echo "Direct pushes to main branch are not allowed"
                  echo "Please create a pull request instead"
                  exit 1
