# Workflow for building and testing the web application

name: Web App CI/CD Pipeline
env:
    SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
    SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
    NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

on:
    push:
        branches: ['main']
        paths:
            # Include web app changes
            - 'apps/web/**'
            # Exclude specific web app paths
            - '!apps/web/supabase/migrations/**'
            - '!apps/web/**/*.md'
            - '!apps/web/**/*.mdx'
            # Include package changes
            - 'packages/**'
            - '!packages/**/*.md'
            - '!packages/**/*.mdx'
            # Include root config files
            - 'package.json'
            - 'pnpm-lock.yaml'
            # Only include this workflow file
            - '.github/workflows/web-actions.yml'
            - '!.github/workflows/supabase-migrations.yml'
            - '!.github/workflows/server-actions.yml'
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: false

defaults:
    run:
        shell: bash
        working-directory: apps/web

jobs:
    build:
        name: Build and Test Web App 🛠️
        runs-on: ubuntu-latest
        env:
            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
            NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v4

            - name: Setup Node.js, pnpm and cache
              uses: wyvox/action-setup-pnpm@v3
              with:
                  node-version: 'lts/*'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run linter
              working-directory: apps/web
              run: pnpm lint

            - name: Build
              working-directory: apps/web
              run: pnpm build
